import pandas as pd

if __name__ == "__main__":
    house = pd.read_csv("data/transformed/houseScraping.tsv", sep = "\t")
    senate = pd.read_csv("data/transformed/senateScraping.tsv", sep = "\t")
    active = pd.read_csv("data/cleaned/candidates_full.csv")
    active = active.loc[active["CAND_ELECTION_YR"] == 2018, ["CAND_ID"]]
    active.columns = ["id"]
    house_active = pd.merge(house, active, on = "id", how = "inner")
    senate_active = pd.merge(senate, active, on = "id", how = "inner")
    house_active[["allRaised"]] = house_active["allRaised"].str.replace("$", "")
    house_active[["allRaised"]] = house_active["allRaised"].str.replace(",", "")
    house_active[["allRaised"]] = pd.to_numeric(house_active["allRaised"])
    house_active[["allIndividuals"]] = house_active["allIndividuals"].str.replace("$", "")
    house_active[["allIndividuals"]] = house_active["allIndividuals"].str.replace(",", "")
    house_active[["allIndividuals"]] = pd.to_numeric(house_active["allIndividuals"])
    house_active[["PACDonations"]] = house_active["PACDonations"].str.replace("$", "")
    house_active[["PACDonations"]] = house_active["PACDonations"].str.replace(",", "")
    house_active[["PACDonations"]] = pd.to_numeric(house_active["PACDonations"])
    house_active[["PartyDonations"]] = house_active["PartyDonations"].str.replace("$", "")
    house_active[["PartyDonations"]] = house_active["PartyDonations"].str.replace(",", "")
    house_active[["PartyDonations"]] = pd.to_numeric(house_active["PartyDonations"])    
    house_active = house_active.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis = 1)
    house_active.to_csv("data/final summary/HouseSummary.csv")

    senate_active[["allRaised"]] = senate_active["allRaised"].str.replace("$", "")
    senate_active[["allRaised"]] = senate_active["allRaised"].str.replace(",", "")
    senate_active[["allRaised"]] = pd.to_numeric(senate_active["allRaised"])
    senate_active[["allIndividuals"]] = senate_active["allIndividuals"].str.replace("$", "")
    senate_active[["allIndividuals"]] = senate_active["allIndividuals"].str.replace(",", "")
    senate_active[["allIndividuals"]] = pd.to_numeric(senate_active["allIndividuals"])
    senate_active[["PACDonations"]] = senate_active["PACDonations"].str.replace("$", "")
    senate_active[["PACDonations"]] = senate_active["PACDonations"].str.replace(",", "")
    senate_active[["PACDonations"]] = pd.to_numeric(senate_active["PACDonations"])
    senate_active[["PartyDonations"]] = senate_active["PartyDonations"].str.replace("$", "")
    senate_active[["PartyDonations"]] = senate_active["PartyDonations"].str.replace(",", "")
    senate_active[["PartyDonations"]] = pd.to_numeric(senate_active["PartyDonations"])
    senate_active = senate_active.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis = 1)
    senate_active.to_csv("data/final summary/SenateSummary.csv")
